### ISSUE TITLE
Nextjs - Window is not defined

### ISSUE THREAD

**Issue by amirizzudin4** [Wufe/react-particles-js#109]
im trying to use this packages in nextjs but i got error saying window is not defined

**Comment by matteobruni** [comment]
@amirizzudin4 have you tried this? https://stackoverflow.com/questions/56319997/nextjs-window-is-not-defined It seems a similar issue

**Comment by Wufe** [comment]
This should be fixed in v3.0.2

**Comment by amirizzudin4** [comment]
I manage to import react particle js in client side rendering following this example
```
import dynamic from 'next/dynamic';

const Typewriter = dynamic(
    () => import('typewriter-effect'),
    {
        ssr: false
    }
)
```

**Comment by ktjd123** [comment]
I think it's not fixed yet. Css breaks when loaded over ssr. Thanks
